name: Vercel Preview

on:
  push:
    branches:
      - master
  pull_request: # This will publish a site preview on every pull request, and also run the build command to test if the site is broken.

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      PR_PATH: pull/${{github.event.number}}
    steps:
      - name: Checkout website repo
        uses: actions/checkout@v3

      - name: Setup Python 
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
        
      - name: Install Dependencies
        run: |
          pip install pyyaml jinja2
    
      - name: Build website
        run: python main.py
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Commit Generated Build"


