name: Vercel Preview

on:
  push:
    branches:
      - master
  pull_request: # This will publish a site preview on every pull request, and also run the build command to test if the site is broken.

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      PR_PATH: pull/${{github.event.number}}
    steps:
      - name: Checkout website repo
        uses: actions/checkout@v2
        with:
          submodules: true # fetch the theme
          # you need to set this as an environment env if your repo or any submodules (e.g the theme) is private:
          # token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Setup Python 
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
        
      - name: Install Dependencies
        run: |
          pip install pyyaml jinja2
    
      - name: Build website
        run: python main.py

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./
